# Generated by Django 3.2.7 on 2021-10-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuitarComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('features', models.TextField()),
                ('score', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='guitarComercial/image/')),
                ('video', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GuitarHandMade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('features', models.TextField()),
                ('score', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='guitarHandMade/image/')),
                ('video', models.CharField(max_length=255)),
                ('luthier', models.CharField(max_length=50)),
                ('luthier_history', models.TextField()),
                ('country', models.CharField(max_length=30)),
            ],
        ),
    ]
