# Generated by Django 3.2.7 on 2021-10-11 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guitars', '0004_punctuation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PunctuationComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveIntegerField()),
                ('guuitar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='guitars.guitarcomercial')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PunctuationHandMade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveIntegerField()),
                ('guuitar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='guitars.guitarhandmade')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Punctuation',
        ),
    ]
